import numpy as np
from numpy.testing import assert_allclose
from numpy.typing import NDArray

from multiads.assembly import Aircraft, AirfoilNACA4, Environment, Section, Span, Wing
from multiads.disciplines import UserDefined
from multiads.disciplines.stability_control import StabilityAndControl
from multiads.disciplines.weight_and_balance import WeightAndBalance
from multiads.scenario import (
    MADSScenario,
    VariableFloat,
    VariableFloatNP,
)
from multiads.scenario.aero_derivatives import AeroDerivativesVariable
from multiads.scenario.stability_control_properties import StabilityControlVariable
from multiads.solvers.stability_control.snc import LinearStabilityControl
from multiads.solvers.stability_control.snc import Options as SCOptions
from multiads.solvers.weight_and_balance.wnb import WB
from multiads.solvers.weight_and_balance.wnb import Options as WBOptions
from multiads.utilities import units


def test_snc() -> None:
    # Design variables
    mass_aircraft = VariableFloat(name="mass", value=8000.0, lb=500, ub=10000.0)
    cg_xpos = VariableFloat(name="cg_xpos", value=5.0, lb=0.0, ub=10.0)

    # Coupling variable
    cg_pos = VariableFloatNP(name="cg_pos", value=np.zeros(3))

    # Components
    env = Environment(
        name="environment",
        height=0.0,
        speed=150.0 * units.kt,
    )

    wing = Wing(
        name="wing",
        mass=mass_aircraft,
        global_pos=cg_pos,
        sections=[
            Section(
                name="sec_1",
                airfoil=AirfoilNACA4("airfoil_1", 1, 2, 24),
                chord=2.0,
                twist=0.0,
            ),
            Section(
                name="sec_2",
                airfoil=AirfoilNACA4("airfoil_2", 2, 2, 12),
                chord=1.0,
                twist=-1.0,
            ),
        ],
        spans=[
            Span(name="span_1", length=10.0, sweep=5.0, dihed=2.0),
        ],
    )

    aircraft = Aircraft(
        name="Aircraft",
        mass=mass_aircraft,
        global_pos=cg_pos,
    )

    aero_deriv = AeroDerivativesVariable.zeros(name=f"{aircraft.name}.aero_derivatives")

    # define dummy fucntion to assign derivatives
    def aeroderivative_user() -> NDArray[np.float64]:
        aero_derivatives = np.array(aero_deriv.value_np, copy=True)
        aero_derivatives[0] = 0.4
        return aero_derivatives

    # define user defined discipline
    aero_der = UserDefined(
        name="Aero Derivatives",
        inputs=[],
        outputs=[aero_deriv],
        expression=aeroderivative_user,
    )

    # Geometry discipline
    geometry = UserDefined(
        name="Geometry",
        inputs=[cg_xpos],
        outputs=[cg_pos],
        expression="[cg_xpos[0], 1.0, 0.5]",
    )

    # Weight and Balance
    solver_wb = WB(
        options=WBOptions(
            non_linear_inertia_factor=1.0,
            inertia_vector=np.array(
                [100.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            ),
        ),
    )

    # Discipline W&B
    meas_weight = WeightAndBalance(
        name="Weight",
        components=[aircraft, wing],
        solver=solver_wb,
    )

    # Solver
    solver = LinearStabilityControl(
        options=SCOptions(
            gravitation=9.81,
            aero_property_type="body",
        ),
    )

    # Discipline
    stability_char = StabilityAndControl(
        name="SnC",
        components=[env, aircraft],
        solver=solver,
    )

    # missing variables  to be generated by fluid-dynamic simulation
    aero_forces = StabilityControlVariable.zeros(
        f"{aircraft.name}.stability_control_properties",
    )

    # define dummy function forces
    def aeroforces_user() -> NDArray[np.float64]:
        aero_forces_dummy = np.array(aero_forces.value_np, copy=True)
        aero_forces_dummy[5] = 100.0
        aero_forces_dummy[3] = 20.0
        return aero_forces_dummy

    # define user defined discipline
    aero_force = UserDefined(
        name="Aero-Dummy",
        inputs=[],
        outputs=[aero_forces],
        expression=aeroforces_user,
    )

    # Scenario
    scenario = MADSScenario()
    scenario.fill_parameter_space([mass_aircraft, cg_xpos])
    scenario.create_scenario(
        disciplines=[geometry, meas_weight, aero_force, aero_der, stability_char],
        formulation="DisciplinaryOpt",
        objective_name=f"{aircraft.name}.static_margin",
        scenario_type="DOE",
    )

    scenario.add_observables([f"{aircraft.name}.mass_properties"])
    scenario.xdsmize()

    scenario.execute(algo_name="PYDOE_FULLFACT", n_samples=4)

    # Post process
    data = scenario.to_dataset()
    data_w = data["designs"][mass_aircraft.name][0]
    data_x = data["designs"][cg_xpos.name][0]
    data_sm = data["functions"][f"{aircraft.name}.static_margin"][0]
    data_iy = data["functions"][f"{aircraft.name}.mass_properties"][6]

    assert_allclose(data_w, [500.0, 10000.0, 500.0, 10000.0])
    assert_allclose(data_x, [0.0, 0.0, 10.0, 10.0])
    assert_allclose(data_sm, [0.0, 0.0, -1000.0, -1000.0])
    assert_allclose(data_iy, [25.0, 25.0, 10025.0, 10025.0])
