import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import spearmanr


from gemseo.datasets.dataset import Dataset

# Load the CSV file generated by comparison_DUST__aero_lf.py
file_path = r'./dataset_export_DUST_aero_lf.csv'

dataset_DUST_aero_lf = pd.read_csv(file_path)

total_number_of_elem = 140

# Access the row which contains the variables ("VARIABLE", index 0)
variables = dataset_DUST_aero_lf.iloc[0]

# Extract the required columns
y_cen_LF = ((dataset_DUST_aero_lf[variables[variables == 'spanload_lf'].index].iloc[2:, 0 : total_number_of_elem]).apply(pd.to_numeric)).to_numpy()
y_span_LF = ((dataset_DUST_aero_lf[variables[variables == 'spanload_lf'].index].iloc[2:, total_number_of_elem : 2*total_number_of_elem]).apply(pd.to_numeric)).to_numpy()
drag_LF = ((dataset_DUST_aero_lf[variables[variables == 'spanload_lf'].index].iloc[2:, 2*total_number_of_elem : 3*total_number_of_elem]).apply(pd.to_numeric)).to_numpy()
lateral_force_LF = ((dataset_DUST_aero_lf[variables[variables == 'spanload_lf'].index].iloc[2:, 3*total_number_of_elem : 4*total_number_of_elem]).apply(pd.to_numeric)).to_numpy()
lift_LF = ((dataset_DUST_aero_lf[variables[variables == 'spanload_lf'].index].iloc[2:, 4*total_number_of_elem : 5*total_number_of_elem]).apply(pd.to_numeric)).to_numpy()
pitch_moment_LF = ((dataset_DUST_aero_lf[variables[variables == 'spanload_lf'].index].iloc[2:, 5*total_number_of_elem : 6*total_number_of_elem]).apply(pd.to_numeric)).to_numpy()
integral_lift_LF = ((dataset_DUST_aero_lf[variables[variables == 'lift_lf'].index].iloc[2:, :]).apply(pd.to_numeric)).to_numpy()
integral_drag_LF = ((dataset_DUST_aero_lf[variables[variables == 'drag_lf'].index].iloc[2:, :]).apply(pd.to_numeric)).to_numpy()

y_cen_DUST = ((dataset_DUST_aero_lf[variables[variables == 'spanload'].index].iloc[2:, 0:total_number_of_elem]).apply(pd.to_numeric)).to_numpy()
y_span_DUST = ((dataset_DUST_aero_lf[variables[variables == 'spanload'].index].iloc[2:, total_number_of_elem : 2*total_number_of_elem]).apply(pd.to_numeric)).to_numpy()
drag_DUST = ((dataset_DUST_aero_lf[variables[variables == 'spanload'].index].iloc[2:, 2*total_number_of_elem : 3*total_number_of_elem]).apply(pd.to_numeric)).to_numpy()
lateral_force_DUST = ((dataset_DUST_aero_lf[variables[variables == 'spanload'].index].iloc[2:, 3*total_number_of_elem : 4*total_number_of_elem]).apply(pd.to_numeric)).to_numpy()
lift_DUST = ((dataset_DUST_aero_lf[variables[variables == 'spanload'].index].iloc[2:, 4*total_number_of_elem : 5*total_number_of_elem]).apply(pd.to_numeric)).to_numpy()
pitch_moment_DUST = ((dataset_DUST_aero_lf[variables[variables == 'spanload'].index].iloc[2:, 5*total_number_of_elem : 6*total_number_of_elem]).apply(pd.to_numeric)).to_numpy()
integral_lift_DUST = ((dataset_DUST_aero_lf[variables[variables == 'lift'].index].iloc[2:, :]).apply(pd.to_numeric)).to_numpy()
integral_drag_DUST = ((dataset_DUST_aero_lf[variables[variables == 'drag'].index].iloc[2:, :]).apply(pd.to_numeric)).to_numpy()

# Extract input parameters
alpha = ((dataset_DUST_aero_lf[variables[variables == 'alpha'].index].iloc[2:, :]).apply(pd.to_numeric)).to_numpy()
angle_root = ((dataset_DUST_aero_lf[variables[variables == 'angle_root'].index].iloc[2:, :]).apply(pd.to_numeric)).to_numpy()
angle_tip = ((dataset_DUST_aero_lf[variables[variables == 'angle_tip'].index].iloc[2:, :]).apply(pd.to_numeric)).to_numpy()
chord_tip = ((dataset_DUST_aero_lf[variables[variables == 'chord_tip'].index].iloc[2:, :]).apply(pd.to_numeric)).to_numpy()
span_0 = ((dataset_DUST_aero_lf[variables[variables == 'span_0'].index].iloc[2:, :]).apply(pd.to_numeric)).to_numpy()


# Calculate the range for the true vs actual line
min_val_lift = min(integral_lift_DUST.min(), integral_lift_LF.min())
max_val_lift = max(integral_lift_DUST.max(), integral_lift_LF.max())
min_val_drag = min(integral_drag_DUST.min(), integral_drag_LF.min())
max_val_drag = max(integral_drag_DUST.max(), integral_drag_LF.max())

min_val_lift_spanwise = min(lift_DUST.min(), lift_LF.min())
max_val_lift_spanwise = max(lift_DUST.max(), lift_LF.max())
min_val_drag_spanwise = min(drag_DUST.min(), drag_LF.min())
max_val_drag_spanwise = max(drag_DUST.max(), drag_LF.max())
min_val_pitch_mom_spanwise = min(pitch_moment_DUST.min(), pitch_moment_LF.min())
max_val_pitch_mom_spanwise = max(pitch_moment_DUST.max(), pitch_moment_LF.max())

# Add some margin for better visualization
margin = 0.1
x_range_lift = np.linspace(min_val_lift - margin, max_val_lift + margin, 100)
x_range_drag = np.linspace(min_val_drag - margin, max_val_drag + margin, 100)
x_range_lift_spanwise = np.linspace(min_val_lift_spanwise - margin, max_val_lift_spanwise + margin, 100)
x_range_drag_spanwise = np.linspace(min_val_drag_spanwise - margin, max_val_drag_spanwise + margin, 100)
x_range_pitch_mom_spanwise = np.linspace(min_val_pitch_mom_spanwise - margin, max_val_pitch_mom_spanwise + margin, 100)

# Calculate R-squared for integral lift
mean_lift_LF = integral_lift_LF.mean()
mean_lift_DUST = integral_lift_DUST.mean()
SST_lift = ((integral_lift_LF - mean_lift_LF) ** 2).sum()
SSR_lift = ((integral_lift_LF - integral_lift_DUST) ** 2).sum()
R_squared_lift = 1 - (SSR_lift / SST_lift)

# Calculate R-squared for integral drag
mean_drag_LF = integral_drag_LF.mean()
mean_drag_DUST = integral_drag_DUST.mean()
SST_drag = ((integral_drag_LF - mean_drag_LF) ** 2).sum()
SSR_drag = ((integral_drag_LF - integral_drag_DUST) ** 2).sum()
R_squared_drag = 1 - (SSR_drag / SST_drag)

# Calculate R-squared for spanwise lift
mean_lift_LF_spanwise = lift_LF.mean()
mean_lift_DUST_spanwise = lift_DUST.mean()
SST_lift_spanwise = ((lift_LF - mean_lift_LF_spanwise) ** 2).sum()
SSR_lift_spanwise = ((lift_LF - lift_DUST) ** 2).sum()
R_squared_lift_spanwise = 1 - (SSR_lift_spanwise / SST_lift_spanwise)

# Calculate R-squared for spanwise drag
mean_drag_LF_spanwise = drag_LF.mean()
mean_drag_DUST_spanwise = drag_DUST.mean()
SST_drag_spanwise = ((drag_LF - mean_drag_LF_spanwise) ** 2).sum()
SSR_drag_spanwise = ((drag_LF - drag_DUST) ** 2).sum()
R_squared_drag_spanwise = 1 - (SSR_drag_spanwise / SST_drag_spanwise)

# Calculate R-squared for spanwise pitching moment
mean_pitch_mom_LF_spanwise = pitch_moment_LF.mean()
mean_pitch_mom_DUST_spanwise = pitch_moment_DUST.mean()
SST_pitch_mom_spanwise = ((pitch_moment_LF - mean_pitch_mom_LF_spanwise) ** 2).sum()
SSR_pitch_mom_spanwise = ((pitch_moment_LF - pitch_moment_DUST) ** 2).sum()
R_squared_pitch_mom_spanwise = 1 - (SSR_pitch_mom_spanwise / SST_pitch_mom_spanwise)

# Calculate Spearman correlation coefficients and p-values
spearman_lift, p_lift = spearmanr(integral_lift_DUST.flatten(), integral_lift_LF.flatten())
spearman_drag, p_drag = spearmanr(integral_drag_DUST.flatten(), integral_drag_LF.flatten())
spearman_lift_spanwise, p_lift_spanwise = spearmanr(lift_DUST.flatten(), lift_LF.flatten())
spearman_drag_spanwise, p_drag_spanwise = spearmanr(drag_DUST.flatten(), drag_LF.flatten())
spearman_pitch_mom_spanwise, p_pitch_mom_spanwise = spearmanr(pitch_moment_DUST.flatten(), pitch_moment_LF.flatten())

# Plotting
plt.figure()
plt.scatter(integral_lift_DUST, integral_lift_LF, label='Data Points')
plt.plot(x_range_lift, x_range_lift, 'r', label='True vs Actual Line')
plt.xlabel('Integral Lift DUST')
plt.ylabel('Integral Lift LF')
plt.title(f'Integral Lift DUST vs LF \n (R^2 = {R_squared_lift:.4f}, Spearman = {spearman_lift:.4f}, p = {p_lift:.4f})')
plt.legend()
plt.savefig('integral_lift_comparison.png')  # Save the figure
plt.close()

plt.figure()
plt.scatter(integral_drag_DUST, integral_drag_LF, label='Data Points')
plt.plot(x_range_drag, x_range_drag, 'r', label='True vs Actual Line')
plt.xlabel('Integral Drag DUST')
plt.ylabel('Integral Drag LF')
plt.title(f'Integral Drag DUST vs LF \n (R^2 = {R_squared_drag:.4f}, Spearman = {spearman_drag:.4f}, p = {p_drag:.4f})')
plt.legend()
plt.savefig('integral_drag_comparison.png')  # Save the figure
plt.close()

# Print R-squared and Spearman values
print(f'R-squared for Integral Lift: {R_squared_lift:.4f}, Spearman: {spearman_lift:.4f}, p: {p_lift:.4f}')
print(f'R-squared for Integral Drag: {R_squared_drag:.4f}, Spearman: {spearman_drag:.4f}, p: {p_drag:.4f}')

# Plot all spanwise lift loads of LF vs the spanwise loads of DUST
plt.figure()
for i in range(total_number_of_elem):
    plt.scatter(lift_DUST[:, i], lift_LF[:, i], color='blue')
plt.plot(x_range_lift_spanwise, x_range_lift_spanwise, 'r', label='True vs Actual Line')
plt.xlabel('Spanwise Lift Loads DUST')
plt.ylabel('Spanwise Lift Loads LF')
plt.title(f'Spanwise Lift Loads DUST vs LF \n (R^2 = {R_squared_lift_spanwise:.4f}, Spearman = {spearman_lift_spanwise:.4f}, p = {p_lift_spanwise:.4f})')
plt.legend()
plt.savefig('spanwise_lift_comparison.png')  # Save the figure
plt.close()

# Plot all spanwise drag loads of LF vs the spanwise loads of DUST
plt.figure()
for i in range(total_number_of_elem):
    plt.scatter(drag_DUST[:, i], drag_LF[:, i], color='blue')
plt.plot(x_range_drag_spanwise, x_range_drag_spanwise, 'r', label='True vs Actual Line')
plt.xlabel('Spanwise Drag Loads DUST')
plt.ylabel('Spanwise Drag Loads LF')
plt.title(f'Spanwise Drag Loads DUST vs LF \n (R^2 = {R_squared_drag_spanwise:.4f}, Spearman = {spearman_drag_spanwise:.4f}, p = {p_drag_spanwise:.4f})')
plt.legend()
plt.savefig('spanwise_drag_comparison.png')  # Save the figure
plt.close()

# Plot all spanwise pitching moment loads of LF vs the spanwise loads of DUST
plt.figure()
for i in range(total_number_of_elem):
    plt.scatter(pitch_moment_DUST[:, i], pitch_moment_LF[:, i], color='blue')
plt.plot(x_range_pitch_mom_spanwise, x_range_pitch_mom_spanwise, 'r', label='True vs Actual Line')
plt.xlabel('Spanwise Pitching Moment Loads DUST')
plt.ylabel('Spanwise Pitching Moment Loads LF')
plt.title(f'Spanwise Pitching Moment Loads DUST vs LF \n (R^2 = {R_squared_pitch_mom_spanwise:.4f}, Spearman = {spearman_pitch_mom_spanwise:.4f}, p = {p_pitch_mom_spanwise:.4f})')
plt.legend()
plt.savefig('spanwise_pitching_moment_comparison.png')  # Save the figure
plt.close()

# Print R-squared and Spearman values for spanwise loads
print(f'R-squared for Spanwise Lift: {R_squared_lift_spanwise:.4f}, Spearman: {spearman_lift_spanwise:.4f}, p: {p_lift_spanwise:.4f}')
print(f'R-squared for Spanwise Drag: {R_squared_drag_spanwise:.4f}, Spearman: {spearman_drag_spanwise:.4f}, p: {p_drag_spanwise:.4f}')
print(f'R-squared for Spanwise Pitching Moment: {R_squared_pitch_mom_spanwise:.4f}, Spearman: {spearman_pitch_mom_spanwise:.4f}, p: {p_pitch_mom_spanwise:.4f}')






# Calculate residuals
residuals_lift = lift_LF - lift_DUST
residuals_drag = drag_LF - drag_DUST
residuals_pitch_mom = pitch_moment_LF - pitch_moment_DUST

# Function to plot residuals against input parameters
def plot_residuals_y_cen(input_param, residuals, title, ylabel):
    plt.figure()
    for i in range(total_number_of_elem):
        plt.scatter(input_param[:, i], residuals[:, i], color='blue', alpha=0.5)
    plt.xlabel('Input Parameter')
    plt.ylabel(ylabel)
    plt.title(title)
    plt.savefig(f'{title.replace(" ", "_")}.png')  # Save the figure
    plt.close()

def plot_residuals(input_param, residuals, title, ylabel):
    plt.figure()
    plt.scatter(input_param, residuals[:], color='blue', alpha=0.5)
    plt.xlabel('Input Parameter')
    plt.ylabel(ylabel)
    plt.title(title)
    plt.savefig(f'{title.replace(" ", "_")}.png')  # Save the figure
    plt.close()


# Plot residuals against y_cen_LF
plot_residuals_y_cen(y_cen_LF, residuals_lift, 'Residuals of Spanwise Lift Loads vs y_cen_LF', 'Residuals of Spanwise Lift Loads')
plot_residuals_y_cen(y_cen_LF, residuals_drag, 'Residuals of Spanwise Drag Loads vs y_cen_LF', 'Residuals of Spanwise Drag Loads')
plot_residuals_y_cen(y_cen_LF, residuals_pitch_mom, 'Residuals of Spanwise Pitching Moment Loads vs y_cen_LF', 'Residuals of Spanwise Pitching Moment Loads')

# Calculate mean residuals over the spanwise elements
mean_residuals_lift = residuals_lift.mean(axis=1)
mean_residuals_drag = residuals_drag.mean(axis=1)
mean_residuals_pitch_mom = residuals_pitch_mom.mean(axis=1)

# Plot mean residuals against alpha
plot_residuals(alpha, mean_residuals_lift, 'Mean Residuals of Spanwise Lift Loads vs alpha', 'Mean Residuals of Spanwise Lift Loads')
plot_residuals(alpha, mean_residuals_drag, 'Mean Residuals of Spanwise Drag Loads vs alpha', 'Mean Residuals of Spanwise Drag Loads')
plot_residuals(alpha, mean_residuals_pitch_mom, 'Mean Residuals of Spanwise Pitching Moment Loads vs alpha', 'Mean Residuals of Spanwise Pitching Moment Loads')

# Plot mean residuals against angle_root
plot_residuals(angle_root, mean_residuals_lift, 'Mean Residuals of Spanwise Lift Loads vs angle_root', 'Mean Residuals of Spanwise Lift Loads')
plot_residuals(angle_root, mean_residuals_drag, 'Mean Residuals of Spanwise Drag Loads vs angle_root', 'Mean Residuals of Spanwise Drag Loads')
plot_residuals(angle_root, mean_residuals_pitch_mom, 'Mean Residuals of Spanwise Pitching Moment Loads vs angle_root', 'Mean Residuals of Spanwise Pitching Moment Loads')

# Plot mean residuals against angle_tip
plot_residuals(angle_tip, mean_residuals_lift, 'Mean Residuals of Spanwise Lift Loads vs angle_tip', 'Mean Residuals of Spanwise Lift Loads')
plot_residuals(angle_tip, mean_residuals_drag, 'Mean Residuals of Spanwise Drag Loads vs angle_tip', 'Mean Residuals of Spanwise Drag Loads')
plot_residuals(angle_tip, mean_residuals_pitch_mom, 'Mean Residuals of Spanwise Pitching Moment Loads vs angle_tip', 'Mean Residuals of Spanwise Pitching Moment Loads')

# Plot mean residuals against chord_tip
plot_residuals(chord_tip, mean_residuals_lift, 'Mean Residuals of Spanwise Lift Loads vs chord_tip', 'Mean Residuals of Spanwise Lift Loads')
plot_residuals(chord_tip, mean_residuals_drag, 'Mean Residuals of Spanwise Drag Loads vs chord_tip', 'Mean Residuals of Spanwise Drag Loads')
plot_residuals(chord_tip, mean_residuals_pitch_mom, 'Mean Residuals of Spanwise Pitching Moment Loads vs chord_tip', 'Mean Residuals of Spanwise Pitching Moment Loads')

# Plot mean residuals against span_0
plot_residuals(span_0, mean_residuals_lift, 'Mean Residuals of Spanwise Lift Loads vs span_0', 'Mean Residuals of Spanwise Lift Loads')
plot_residuals(span_0, mean_residuals_drag, 'Mean Residuals of Spanwise Drag Loads vs span_0', 'Mean Residuals of Spanwise Drag Loads')
plot_residuals(span_0, mean_residuals_pitch_mom, 'Mean Residuals of Spanwise Pitching Moment Loads vs span_0', 'Mean Residuals of Spanwise Pitching Moment Loads')